// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

// Mod
archives_base_name=RS_CraftingMonitorInGrid
maven_group=gisellevonbingen.rs_cmig
mod_id=rs_cmig
mod_version=6.0
mod_name=RS: CraftingMonitorInGrid
mod_description=Add crafting monitor button in grid
mod_license=MIT
mod_homepage=https://curseforge.com/minecraft/mc-mods/rs-crafting-monitor-in-grid
mod_source=https://github.com/gisellevonbingen/Minecraft-CraftingMonitorInGrid
mod_issues=https://github.com/gisellevonbingen/Minecraft-CraftingMonitorInGrid/issues

// Minecraft, Mod Loader
mc_version=1.21.1
neoforge_loader_version=4
neoforge_api_version=21.1.9
neoforge_api_version_range=[21.1.0,)

// Required
refined_storage_version=2.0.0
refined_storage_version_range=[0,)
refined_storage_file=6358597

// Runtime Only
jei_version=19.19.6.235
jade_file=6155158
